.TH "md_CHANGELOG" 3 "Wed Feb 12 2020" "Version v0.4.0" "smxrts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG`v0\&.3\&.2` (latest) 
 \- 
.SS "Bug Fixes"
.PP
.IP "\(bu" 2
now, general boolean properties of a net are read correctly\&.
.IP "\(bu" 2
first check message type filter, then check message content filter\&.
.PP
.PP
.PP
 
.SH "\fCv0\&.3\&.1\fP"
.PP
.PP
.SS "Changes"
.PP
.IP "\(bu" 2
Log version numbers on level NOTICE\&.
.IP "\(bu" 2
Log RTS version number\&.
.PP
.PP
.PP
 
.SH "\fCv0\&.3\&.0\fP"
.PP
.PP
.SS "Bug Fixes"
.PP
.IP "\(bu" 2
fix some typos
.IP "\(bu" 2
exclude channel macro to set content filter from testing clause
.PP
.PP
.SS "New Features"
.PP
.IP "\(bu" 2
Allow to configure whether a message is backed up in a decoupled channel\&.
.PP
.PP
.PP
 
.SH "\fCv0\&.2\&.1\fP"
.PP
.PP
.SS "Bug Fixes"
.PP
.IP "\(bu" 2
fix deadline miss reports on non-TT nets (#16)
.PP
.PP
.SS "Changes"
.PP
.IP "\(bu" 2
Remove XML configuration
.IP "\(bu" 2
Remove Streamix-based profiling
.IP "\(bu" 2
Improve deadline detection handling (#16)
.IP "\(bu" 2
Remove the message type \fCtsmem\fP from the RTS and created an external library instead (\fClibsmxmsgtsmem\fP)
.PP
.PP
.SS "New Features"
.PP
.IP "\(bu" 2
Allow to configure the RTS with a JSON file instead of XML (#17)
.IP "\(bu" 2
Create a small configuration API which allows to easily access keys in a JSON configuration file
.IP "\(bu" 2
Allow to address each net instance in configuration (#14)
.IP "\(bu" 2
Allow for sub-configuration files (#7)
.IP "\(bu" 2
Add profiling capabilities with \fClttng\fP (#13)
.IP "\(bu" 2
Allow to check for the reason if a channel read or write operation fails (#8)
.IP "\(bu" 2
Add a test environment that allows to run a single box implementation (#12)
.IP "\(bu" 2
Add a type field to the message structure\&.
.IP "\(bu" 2
Add a macro to access the implementation name\&.
.IP "\(bu" 2
Add a utility function to filter message types\&.
.IP "\(bu" 2
Add generic message type and message content filter functionality that acts upon writing a message to a channel\&. For reasons of performance, the type filter can be disabled globally with a boolean config option \fCtype_filter\fP\&.
.PP
.PP
.PP
 
.SH "\fCv0\&.1\&.0\fP"
.PP
.PP
.SS "Bug Fixes"
.PP
.IP "\(bu" 2
fix the TF read function (#1)
.IP "\(bu" 2
fix the termination behaviour of TF
.IP "\(bu" 2
fix the termination behaviour of RN
.IP "\(bu" 2
Handle potential seg-faults by checking for null pointers consistently
.IP "\(bu" 2
fix mutex locking and unlocking
.IP "\(bu" 2
fix collector counter
.PP
.PP
.SS "Changes"
.PP
.IP "\(bu" 2
Cleanup cond vars (move the cond var from fifo to channel level)
.IP "\(bu" 2
Use a common net structure to store information every net has
.IP "\(bu" 2
Create channel ends to better distinguish between read and write operations
.IP "\(bu" 2
Add new FIFO types to handle special case of TFs (see #1)
.IP "\(bu" 2
Cope with open ports by allowing a channel to be \fCNULL\fP
.IP "\(bu" 2
Pass net handler to msg macros and cleanup function
.IP "\(bu" 2
Restructuring of \fCsmx_tf\fP to make it more similar to a normal net
.IP "\(bu" 2
Synchronize initialisation with a \fCpthread_barrier\fP
.IP "\(bu" 2
Adapt to cope with c template files generated by \fCsmxrtsp\fP
.IP "\(bu" 2
Change the license from GPL-v3\&.0 to MPL-v2\&.0
.PP
.PP
.SS "New Features"
.PP
.IP "\(bu" 2
Add a \fCunpack\fP function to the message callbacks
.IP "\(bu" 2
Allow to configure the RTS with an XML file (path to the file can be passed by parameter)
.IP "\(bu" 2
Pass net-specific configuration to the net instance
.IP "\(bu" 2
Each custom net must now define an init and cleanup function
.IP "\(bu" 2
Propagate termination signals in both directions
.IP "\(bu" 2
Use zlog categories to distinguish between different concept
.IP "\(bu" 2
Include multiple log levels
.IP "\(bu" 2
Make the routing node fair when reading from inputs (a rn has now state)
.IP "\(bu" 2
Allow to configure whether a TF copies msgs on DL miss of the producer or sends a NULL msg (if copy is enabled every msg has to be backed up)
.IP "\(bu" 2
Run TF and TF-framed nets as RT-Tasks with different priorities
.IP "\(bu" 2
Add profiling capabilities (requires a box to capture the profiling events, e\&.g\&. \fCsmx_mogo\fP)
.IP "\(bu" 2
At the end of an app execution log execution time and box execution counts
.PP
.PP
.PP
 
.SH "\fCdiss_final\fP"
.PP
.PP
The initial release after completing the \fCdissertation\fP\&. 
