.TH "smx" 3 "Wed Feb 12 2020" "Version v0.4.0" "smxrts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smx
.SH SYNOPSIS
.br
.PP
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBChannel API\fP"
.br
.ti -1c
.RI "\fBConfiguration API\fP"
.br
.ti -1c
.RI "\fBMessage API\fP"
.br
.ti -1c
.RI "\fBNet API\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBLicense:\fP
.RS 4
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/\&.
.RE
.PP
The runtime system library for Streamix 
.SH "Author"
.PP 
Generated automatically by Doxygen for smxrts from the source code\&.
