.TH "smx_msg_s" 3 "Wed Feb 12 2020" "Version v0.4.0" "smxrts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smx_msg_s \- A Streamix message structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smxtypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBid\fP"
.br
.ti -1c
.RI "char * \fBtype\fP"
.br
.ti -1c
.RI "bool \fBprevent_backup\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "void *(* \fBcopy\fP )(void *, size_t)"
.br
.ti -1c
.RI "void(* \fBdestroy\fP )(void *)"
.br
.ti -1c
.RI "void *(* \fBunpack\fP )(void *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A Streamix message structure\&. 

The structure contains handlers that can be used to manipulate data\&. These handlers are provided by the box implementation\&. 
.SH "Field Documentation"
.PP 
.SS "void*(* smx_msg_s::copy) (void *, size_t)"
pointer to a fct making a deep copy 
.SS "void* smx_msg_s::data"
pointer to the data 
.SS "void(* smx_msg_s::destroy) (void *)"
pointer to a fct that frees data 
.SS "unsigned long smx_msg_s::id"
the unique message id 
.SS "bool smx_msg_s::prevent_backup"
prevents msg backups from being created 
.SS "int smx_msg_s::size"
size of the data 
.SS "char* smx_msg_s::type"
an optional string indicating the msg data type 
.SS "void*(* smx_msg_s::unpack) (void *)"
pointer to a fct that unpacks data 

.SH "Author"
.PP 
Generated automatically by Doxygen for smxrts from the source code\&.
