.TH "smx_channel_end_s" 3 "Wed Feb 12 2020" "Version v0.4.0" "smxrts" \" -*- nroff -*-
.ad l
.nh
.SH NAME
smx_channel_end_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smxtypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsmx_channel_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBsmx_channel_err_t\fP \fBerr\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBch_cv\fP"
.br
.ti -1c
.RI "unsigned long \fBcount\fP"
.br
.ti -1c
.RI "\fBsmx_net_t\fP * \fBnet\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "char ** \fBitems\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "} \fBfilter\fP"
.br
.ti -1c
.RI "bool(* \fBcontent_filter\fP )(\fBsmx_msg_t\fP *msg)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The end of a channel 
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t smx_channel_end_s::ch_cv"
conditional variable to trigger producer 
.SS "bool( * smx_channel_end_s::content_filter) (\fBsmx_msg_t\fP *msg)"
A pointer to the filter function\&. 
.SS "unsigned long smx_channel_end_s::count"
access counter 
.SS "\fBsmx_channel_err_t\fP smx_channel_end_s::err"
error on the channel end 
.SS "struct { \&.\&.\&. }   smx_channel_end_s::filter"
All message types allowed on this channel 
.SS "\fBsmx_net_t\fP* smx_channel_end_s::net"
pointer to the connecting net 
.SS "\fBsmx_channel_state_t\fP smx_channel_end_s::state"
state of the channel end 

.SH "Author"
.PP 
Generated automatically by Doxygen for smxrts from the source code\&.
