/**
 * @file boxgen.c
 *
 * Header definitions of compiled streamix-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL STREAMIX-SOURCE FILE boxgen.smx INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 */

#ifndef BOXGEN_H
#define BOXGEN_H


typedef struct box_A_s {
    void*  port_syn_ack;
    void*  port_ack;
    void*  port_syn;
} box_A_t;

typedef struct box_B_s {
    void*  port_ack;
    void*  port_syn;
    void*  port_syn_ack;
} box_B_t;

void *box_A( void* );
void *box_B( void* );

#endif // BOXGEN_H
