/**
 * @file boxgen.h
 *
 * Source code of compiled streamix-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL STREAMIX-SOURCE FILE boxgen.smx INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 */

#include "boxgen.h"
#include "smxrts.h"
#include <zlog.h>

extern void* a( void* handler );
void* box_A( void* handler )
{
    dzlog_info( "start thread A" );
    a( handler );
    dzlog_info( "end thread A" );
    return NULL;
}

extern void* b( void* handler );
void* box_B( void* handler )
{
    dzlog_info( "start thread B" );
    b( handler );
    dzlog_info( "end thread B" );
    return NULL;
}

