/**
 * @file tcp.h
 *
 * Source code of compiled streamix-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL STREAMIX-SOURCE FILE tcp.smx INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 */

#include "smxrts.h"
#include "boxgen.h"

int main( void )
{
    SMX_PROGRAM_INIT();

    void* box_0 = SMX_BOX_CREATE( A );
    void* box_1 = SMX_BOX_CREATE( B );
    void* ch_0 = SMX_CHANNEL_CREATE();
    SMX_CONNECT( box_1, ch_0, B, syn );
    SMX_CONNECT( box_0, ch_0, A, syn );
    void* ch_1 = SMX_CHANNEL_CREATE();
    SMX_CONNECT( box_0, ch_1, A, syn_ack );
    SMX_CONNECT( box_1, ch_1, B, syn_ack );
    void* ch_2 = SMX_CHANNEL_CREATE();
    SMX_CONNECT( box_1, ch_2, B, ack );
    SMX_CONNECT( box_0, ch_2, A, ack );

    SMX_BOX_RUN( box_0, A );
    SMX_BOX_RUN( box_1, B );

    SMX_BOX_WAIT_END( A );
    SMX_BOX_WAIT_END( B );

    SMX_BOX_DESTROY( box_0 );
    SMX_BOX_DESTROY( box_1 );
    SMX_CHANNEL_DESTROY( ch_0 );
    SMX_CHANNEL_DESTROY( ch_1 );
    SMX_CHANNEL_DESTROY( ch_2 );

    SMX_PROGRAM_CLEANUP();
}

